Создан catalog.html
htmlacademy-htmlcss/528665-sedona-29 pull request #3
Opened 2020-09-21 15:38 UTC by lamentia

Разметка внутренней страницы каталога

2020-09-21 16:03 UTC, Shramkoweb requested changes

2020-09-21 16:03 UTC, Shramkoweb commented on catalog.html
> +                        <label for="cost-from">От
for - не нужен если ты лейблом оборачиваешь инпут

2020-09-21 16:03 UTC, Shramkoweb commented on catalog.html
> +        <section>
Тут отлично подойдет скрытый заголовок - Сортировка

2020-09-21 16:03 UTC, Shramkoweb commented on catalog.html
> +                </div>
Это все один цельный блок, внутри артикла - это блок с информацией о гостиннице.
И тут явно опять пояхало выравнивание

2020-09-21 16:03 UTC, Shramkoweb commented on catalog.html
> +        </html>
В конце каждого файла должна быть пустая строчка.
Проверь, что ты установил editorConfig плагин для VSCode

2020-09-21 16:39 UTC, lamentia commented on catalog.html
> +                </div>
А если второй вариант я заверну так?

<div>
              <h2>Тип жилья:</h2>
<ul>
                <li>
                  <input type="checkbox" name="hotel" id="hotel" checked>
                  <label for="hotel">Гостиница</label>
                </li>
                <li>
                  <input type="checkbox" name="motel" id="motel" checked>
                  <label for="motel">Мотель</label>
                </li>
                <li>
                  <input type="checkbox" name="apartments" id="apartments" checked>
                  <label for="apartments">Апартаменты</label>
                </li>
</ul>
</div>

2020-09-21 16:41 UTC, lamentia commented on catalog.html
> +            <form action="#" method="POST"></form>
Здесь не хватает name="filters" в форме?

2020-09-21 16:42 UTC, lamentia commented on catalog.html
> +                    <li><a href="catalog.html">Гостиницы</a></li>
`<a href="#">Гостиницы</a>` 

Так правильней?

2020-09-21 16:43 UTC, lamentia commented on catalog.html
> +            <img src="img/header_logo.png" width="138" height="70" alt="Лого"/>
`<a href="index.html"><img src="img/header_logo.png" width="138" height="70" alt="Sedona"></a>`

Правильно?

2020-09-21 16:46 UTC, lamentia commented on catalog.html
> +                    <button type="button" name="show">Показать</button>
Не особо понял в чем ошибка с 49 по 51...

name="show" убираю тогда

2020-09-21 16:46 UTC, lamentia commented on catalog.html
> +        <section>
Что такое скрытый заголовок?

2020-09-21 16:48 UTC, lamentia commented on catalog.html
> +                </div>
Не понял про цельный блок

2020-09-21 17:35 UTC, Shramkoweb commented on catalog.html
> +                    <li><a href="catalog.html">Гостиницы</a></li>
да

2020-09-21 17:35 UTC, Shramkoweb commented on catalog.html
> +            <img src="img/header_logo.png" width="138" height="70" alt="Лого"/>
да, но альт - логотип сайта Седона

2020-09-21 17:36 UTC, Shramkoweb commented on catalog.html
> +            <form action="#" method="POST"></form>
Нет, я имею ввиду почему внутри формы ничего?

2020-09-21 17:36 UTC, Shramkoweb commented on catalog.html
> +                </div>
Нет, тут идеально филдсет нужен

2020-09-21 17:38 UTC, Shramkoweb commented on catalog.html
> +                    <button type="button" name="show">Показать</button>
> Не особо понял в чем ошибка с 49 по 51...

Ну как мы с тобой обсуждали, блоки явно выравняны криво

2020-09-21 17:39 UTC, Shramkoweb commented on catalog.html
> +        <section>
Скрытый: значит, что мы его сверстаем, но в макете его нет. Поэтому потом скроем через css
Мы так делали на главной, там где блок был поиска гостинниц

2020-09-27 16:48 UTC, Shramkoweb approved these changes

2020-09-27 16:54 UTC, Shramkoweb requested changes

2020-09-27 16:54 UTC, Shramkoweb commented on catalog.html
> +            <form action="https://echo.htmlacademy.ru/" method="POST"></form>
Пустая форма

2020-09-27 16:54 UTC, Shramkoweb commented on catalog.html
> +        </html>
Не пофиксил

2020-09-27 17:50 UTC, Shramkoweb approved these changes

2020-09-27 17:50 UTC, merged